// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6F5Yq8HJkYEEcTZPHkGZg47ThdZmRas',
    appId: '1:1026343227662:web:c7dafaea1258a6dcc7875f',
    messagingSenderId: '1026343227662',
    projectId: 'myop-myup',
    authDomain: 'myop-myup.firebaseapp.com',
    storageBucket: 'myop-myup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JcB6EO_Sowgvls7IExL6Ubc__1OwpcU',
    appId: '1:1026343227662:android:fd8cc5cf4e474068c7875f',
    messagingSenderId: '1026343227662',
    projectId: 'myop-myup',
    storageBucket: 'myop-myup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXMe0qD_0VHIh79XV49Qc34fRPBgdO_wY',
    appId: '1:1026343227662:ios:873f32d707dd2bb8c7875f',
    messagingSenderId: '1026343227662',
    projectId: 'myop-myup',
    storageBucket: 'myop-myup.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXMe0qD_0VHIh79XV49Qc34fRPBgdO_wY',
    appId: '1:1026343227662:ios:873f32d707dd2bb8c7875f',
    messagingSenderId: '1026343227662',
    projectId: 'myop-myup',
    storageBucket: 'myop-myup.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe6F5Yq8HJkYEEcTZPHkGZg47ThdZmRas',
    appId: '1:1026343227662:web:e58d04ebfb97d03fc7875f',
    messagingSenderId: '1026343227662',
    projectId: 'myop-myup',
    authDomain: 'myop-myup.firebaseapp.com',
    storageBucket: 'myop-myup.firebasestorage.app',
  );
}
